version: 0.0
os: linux
files:
  - source: /pybossa
    destination: /home/ubuntu/pybossa/pybossa
hooks:
  BeforeInstall:
    - location: scripts/pre_install
      timeout: 300
      runas: root  
  AfterInstall:
    - location: scripts/post_install
      timeout: 300
      runas: root        
permissions:
# 1) For newly deployment folder "pybossa" under /home/ubuntu/pybossa/
#  owner = ubuntu, group = ubuntu and mode = 775 (drwxrwxr-x).
  - object: /home/ubuntu/pybossa
    pattern: "pybossa"
    owner: ubuntu
    group: ubuntu
    mode: 775
    type:
      - directory
# 2) For all folders at any level under /home/ubuntu/pybossa/
#  owner = ubuntu, group = ubuntu and mode = 775 (drwxrwxr-x).
  - object: /home/ubuntu/pybossa/pybossa
    owner: ubuntu
    group: ubuntu
    mode: 775
    type:
      - directory
# 3) For all files at any level under /home/ubuntu/pybossa/pybossa
# except pre_install and post_install scripts
#  owner = ubuntu, group = ubuntu and mode = 664 (-rw-rw-r--).
  - object: /home/ubuntu/pybossa/pybossa
    except: [pre_install, post_install]
    owner: ubuntu
    group: ubuntu
    mode: 664
    type:
      - file
