#!/bin/bash
{
# start services
service supervisor restart &
rc=$?; if [[ $rc != 0 ]]; then
echo "error stopping supervisor"
exit $rc;
else
echo "execucted command service supervisor restart"
fi

service nginx restart &
rc=$?; if [[ $rc != 0 ]]; then
echo "error stopping nginx"
exit $rc;
else
echo "execucted command service nginx restart"
fi

# wait  to turn on supervisor and nginx completely
sleep 10

# ensure localhost is up
temp=`curl localhost`
rc=$?; if [[ $rc != 0 ]]; then
echo "error executing curl localhost"
exit $rc;
else
echo "sucessfully deployed new version. passed curl localhost"
fi

} >> /var/log/codedeploy-post-install.log 2>&1
