#!/bin/bash
# stop supervisor and nginx
{
isProcRunning=`pgrep supervisor`
if [[ -n  $isProcRunning ]]; then
    # reset cache
    echo "$(date) clear cache"
    cd /home/ubuntu/pybossa
    source env/bin/activate
    python clear_cache.py

    service supervisor stop &
    echo "$(date) command service supervisor stop, exit code: $?"
fi
isProcRunning=`pgrep nginx`
if [[ -n  $isProcRunning ]]; then
    service nginx stop &
    echo "$(date) executed command service nginx stop, exit code: $?"
fi
# add delay of 10 seconds for supervisor to shut down completely before next installation steps runs
sleep 10

# remove the oldest backup directories, keep most recent 3
ls -t pybossa.* -d | egrep "pybossa\.[0-9]+" | tail -n +3 | xargs rm -rf
#rename target folder by appending current datetime to it
datetimeval=$(date +%m%d%Y%H%M%S)
targetpath=/home/ubuntu/pybossa/pybossa
mv $targetpath $targetpath.$datetimeval
rc=$?; if [[ $rc != 0 ]]; then
echo "$(date) error renaming $targetpath to $targetpath.$datetimeval"
exit $rc;
else
echo "$(date) renamed folder from $targetpath to $targetpath.$datetimeval"
fi

} >> /var/log/codedeploy-pre-install.log
